name: "Update"
on:
  schedule:
  - cron: "42 0 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v9
    - uses: cachix/cachix-action@v6
      with:
        name: manveru
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: ./update.sh
